export const vegetableImages = {
    "חסה": "https://img.rami-levy.co.il/product/123/25/medium.jpg",
    "תפוז": "https://img.rami-levy.co.il/product/122/24/medium.jpg", 
    "קיווי": "https://img.rami-levy.co.il/product/120/22/medium.jpg",
    "אננס": "https://img.rami-levy.co.il/product/119/21/medium.jpg",
    "מנגו": "https://img.rami-levy.co.il/product/118/20/medium.jpg",
    "לימון": "https://img.rami-levy.co.il/product/117/19/medium.jpg",
    "תפוח ירוק": "https://img.rami-levy.co.il/product/116/18/medium.jpg",
    "תפוח צהוב": "https://img.rami-levy.co.il/product/115/17/medium.jpg",
    "תפוח אדום": "https://img.rami-levy.co.il/product/114/16/medium.jpg",
    "אגס": "https://img.rami-levy.co.il/product/113/15/medium.jpg",
    "צנון": "https://img.rami-levy.co.il/product/112/14/medium.jpg",
    "תפוא": "https://img.rami-levy.co.il/product/111/13/medium.jpg",
    "כרוב אדום": "https://img.rami-levy.co.il/product/110/12/medium.jpg",
    "כרוב לבן": "https://img.rami-levy.co.il/product/109/11/medium.jpg",
    "בצל": "https://img.rami-levy.co.il/product/108/10/medium.jpg",
    "קישוא": "https://img.rami-levy.co.il/product/107/9/medium.jpg",
    "חציל": "https://img.rami-levy.co.il/product/106/8/medium.jpg",
    "גמבה": "https://img.rami-levy.co.il/product/105/7/medium.jpg",
    "גמבה אדומה": "https://img.rami-levy.co.il/product/104/6/medium.jpg",
    "גמבה ירוקה": "https://img.rami-levy.co.il/product/103/5/medium.jpg",
    "גזר": "https://img.rami-levy.co.il/product/102/4/medium.jpg",
    "מלפפון": "https://img.rami-levy.co.il/product/101/3/medium.jpg",
    "עגבניה": "https://img.rami-levy.co.il/product/100/2/medium.jpg"
  };